// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.go
// DO NOT EDIT (except nc_double.go).

package netcdf

import (
	"fmt"
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// WriteInt8s writes data as the entire data for variable v.
func (v Var) WriteInt8s(data []int8) error {
	if err := okData(v, BYTE, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_schar(C.int(v.ds), C.int(v.id), (*C.schar)(unsafe.Pointer(&data[0]))))
}

// ReadInt8s reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) ReadInt8s(data []int8) error {
	if err := okData(v, BYTE, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_schar(C.int(v.ds), C.int(v.id), (*C.schar)(unsafe.Pointer(&data[0]))))
}

// WriteInt8s sets the value of attribute a to val.
func (a Attr) WriteInt8s(val []int8) error {
	// We don't need okData here because netcdf library doesn't know
	// the length or type of the attribute yet.
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_schar(C.int(a.v.ds), C.int(a.v.id), cname,
		C.nc_type(BYTE), C.size_t(len(val)), (*C.schar)(unsafe.Pointer(&val[0]))))
}

// ReadInt8s reads the entire attribute value into val.
func (a Attr) ReadInt8s(val []int8) (err error) {
	if err := okData(a, BYTE, len(val)); err != nil {
		return err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	err = newError(C.nc_get_att_schar(C.int(a.v.ds), C.int(a.v.id), cname,
		(*C.schar)(unsafe.Pointer(&val[0]))))
	return
}

// Int8sReader is a interface that allows reading a sequence of values of fixed length.
type Int8sReader interface {
	Len() (n uint64, err error)
	ReadInt8s(val []int8) (err error)
}

// GetInt8s reads the entire data in r and returns it.
func GetInt8s(r Int8sReader) (data []int8, err error) {
	n, err := r.Len()
	if err != nil {
		return
	}
	data = make([]int8, n)
	err = r.ReadInt8s(data)
	return
}

// testReadInt8s writes somes data to v. N is v.Len().
// This function is only used for testing.
func testWriteInt8s(v Var, n uint64) error {
	data := make([]int8, n)
	for i := 0; i < int(n); i++ {
		data[i] = int8(i + 10)
	}
	return v.WriteInt8s(data)
}

// testReadInt8s reads data from v and checks that it's the same as what
// was written by testWriteDouble. N is v.Len().
// This function is only used for testing.
func testReadInt8s(v Var, n uint64) error {
	data := make([]int8, n)
	if err := v.ReadInt8s(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		if val := int8(i + 10); data[i] != val {
			return fmt.Errorf("data at position %d is %v; expected %v\n", i, data[i], val)
		}
	}
	return nil
}
