// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.go
// DO NOT EDIT (except nc_double.go).

package netcdf

import (
	"fmt"
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// WriteFloat64s writes data as the entire data for variable v.
func (v Var) WriteFloat64s(data []float64) error {
	if err := okData(v, DOUBLE, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_double(C.int(v.ds), C.int(v.id), (*C.double)(unsafe.Pointer(&data[0]))))
}

// ReadFloat64s reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) ReadFloat64s(data []float64) error {
	if err := okData(v, DOUBLE, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_double(C.int(v.ds), C.int(v.id), (*C.double)(unsafe.Pointer(&data[0]))))
}

// WriteFloat64s sets the value of attribute a to val.
func (a Attr) WriteFloat64s(val []float64) error {
	// We don't need okData here because netcdf library doesn't know
	// the length or type of the attribute yet.
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_double(C.int(a.v.ds), C.int(a.v.id), cname,
		C.nc_type(DOUBLE), C.size_t(len(val)), (*C.double)(unsafe.Pointer(&val[0]))))
}

// ReadFloat64s reads the entire attribute value into val.
func (a Attr) ReadFloat64s(val []float64) (err error) {
	if err := okData(a, DOUBLE, len(val)); err != nil {
		return err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	err = newError(C.nc_get_att_double(C.int(a.v.ds), C.int(a.v.id), cname,
		(*C.double)(unsafe.Pointer(&val[0]))))
	return
}

// ReadFloat64At returns a value via index position
func (v Var) ReadFloat64At(idx []uint64) (val float64, err error) {
	var dimPtr *C.size_t
	if len(idx) > 0 {
		dimPtr = (*C.size_t)(unsafe.Pointer(&idx[0]))
	}
	err = newError(C.nc_get_var1_double(C.int(v.ds), C.int(v.id),
		dimPtr, (*C.double)(unsafe.Pointer(&val))))
	return
}

// WriteFloat64At sets a value via its index position
func (v Var) WriteFloat64At(idx []uint64, val float64) (err error) {
	var dimPtr *C.size_t
	if len(idx) > 0 {
		dimPtr = (*C.size_t)(unsafe.Pointer(&idx[0]))
	}
	err = newError(C.nc_put_var1_double(C.int(v.ds), C.int(v.id),
		dimPtr, (*C.double)(unsafe.Pointer(&val))))
	return
}

// WriteFloat64Slice writes data as a slice of variable v. The slice is specified by start and count:
// https://www.unidata.ucar.edu/software/netcdf/docs/programming_notes.html#specify_hyperslab.
func (v Var) WriteFloat64Slice(data []float64, start, count []uint64) error {
	if err := okDataSlice(v, DOUBLE, len(data), start, count); err != nil {
		return err
	}
	return newError(C.nc_put_vara_double(C.int(v.ds), C.int(v.id),
		(*C.size_t)(unsafe.Pointer(&start[0])),
		(*C.size_t)(unsafe.Pointer(&count[0])),
		(*C.double)(unsafe.Pointer(&data[0])),
	))
}

// ReadFloat64Slice reads a slice of variable v into data, which must have enough
// space for all the values. The slice is specified by start and count:
// https://www.unidata.ucar.edu/software/netcdf/docs/programming_notes.html#specify_hyperslab.
func (v Var) ReadFloat64Slice(data []float64, start, count []uint64) error {
	if err := okDataSlice(v, DOUBLE, len(data), start, count); err != nil {
		return err
	}
	return newError(C.nc_get_vara_double(C.int(v.ds), C.int(v.id),
		(*C.size_t)(unsafe.Pointer(&start[0])),
		(*C.size_t)(unsafe.Pointer(&count[0])),
		(*C.double)(unsafe.Pointer(&data[0])),
	))
}

// WriteFloat64StridedSlice writes data as a slice of variable v. The slice is specified by start, count and stride:
// https://www.unidata.ucar.edu/software/netcdf/docs/programming_notes.html#specify_hyperslab.
func (v Var) WriteFloat64StridedSlice(data []float64, start, count []uint64, stride []int64) error {
	if err := okDataStride(v, DOUBLE, len(data), start, count, stride); err != nil {
		return err
	}
	return newError(C.nc_put_vars_double(C.int(v.ds), C.int(v.id),
		(*C.size_t)(unsafe.Pointer(&start[0])),
		(*C.size_t)(unsafe.Pointer(&count[0])),
		(*C.ptrdiff_t)(unsafe.Pointer(&stride[0])),
		(*C.double)(unsafe.Pointer(&data[0])),
	))
}

// ReadFloat64StridedSlice reads a strided slice of variable v into data, which must have enough
// space for all the values. The slice is specified by start, count and stride:
// https://www.unidata.ucar.edu/software/netcdf/docs/programming_notes.html#specify_hyperslab.
func (v Var) ReadFloat64StridedSlice(data []float64, start, count []uint64, stride []int64) error {
	if err := okDataStride(v, DOUBLE, len(data), start, count, stride); err != nil {
		return err
	}
	return newError(C.nc_get_vars_double(C.int(v.ds), C.int(v.id),
		(*C.size_t)(unsafe.Pointer(&start[0])),
		(*C.size_t)(unsafe.Pointer(&count[0])),
		(*C.ptrdiff_t)(unsafe.Pointer(&stride[0])),
		(*C.double)(unsafe.Pointer(&data[0])),
	))
}

// Float64sReader is a interface that allows reading a sequence of values of fixed length.
type Float64sReader interface {
	Len() (n uint64, err error)
	ReadFloat64s(val []float64) (err error)
}

// GetFloat64s reads the entire data in r and returns it.
func GetFloat64s(r Float64sReader) (data []float64, err error) {
	n, err := r.Len()
	if err != nil {
		return
	}
	data = make([]float64, n)
	err = r.ReadFloat64s(data)
	return
}

// testReadFloat64s writes somes data to v. N is v.Len().
// This function is only used for testing.
func testWriteFloat64s(v Var, n uint64) error {
	data := make([]float64, n)
	for i := 0; i < int(n); i++ {
		data[i] = float64(i + 10)
	}
	return v.WriteFloat64s(data)
}

// testReadFloat64s reads data from v and checks that it's the same as what
// was written by testWriteDouble. N is v.Len().
// This function is only used for testing.
func testReadFloat64s(v Var, n uint64) error {
	data := make([]float64, n)
	if err := v.ReadFloat64s(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		if val := float64(i + 10); data[i] != val {
			return fmt.Errorf("data at position %d is %v; expected %v", i, data[i], val)
		}
	}
	return nil
}

// testWriteFloat64Slice writes somes data to v. N is v.LenDim().
// This function is only used for testing.
func testWriteFloat64Slice(v Var, n []uint64) error {
	if len(n) == 0 {
		return nil // Don't test empty data.
	}
	start, count := make([]uint64, len(n)), make([]uint64, len(n))
	for i, v := range n {
		start[i] = v / 2
		count[i] = v / 2
	}
	data := make([]float64, product(count))
	for i := 0; i < int(product(count)); i++ {
		data[i] = float64(i + 10)
	}
	return v.WriteFloat64Slice(data, start, count)
}

// testReadFloat64Slice reads data from v and checks that it's the same as what
// was written by testWriteDouble. N is v.LenDim().
// This function is only used for testing.
func testReadFloat64Slice(v Var, n []uint64) error {
	if len(n) == 0 {
		return nil // Don't test empty data.
	}
	start, count := make([]uint64, len(n)), make([]uint64, len(n))
	for i, v := range n {
		start[i] = v / 2
		count[i] = v / 2
	}
	data := make([]float64, product(count))
	if err := v.ReadFloat64Slice(data, start, count); err != nil {
		return err
	}
	for i := 0; i < int(product(count)); i++ {
		if val := float64(i + 10); data[i] != val {
			return fmt.Errorf("strided slice data at position %d is %v; expected %v", i, data[i], val)
		}
	}
	return nil
}

// testWriteFloat64StridedSlice writes somes data to v. N is v.LenDim().
// This function is only used for testing.
func testWriteFloat64StridedSlice(v Var, n []uint64) error {
	if len(n) == 0 {
		return nil // Don't test empty data.
	}
	start, count, stride := make([]uint64, len(n)), make([]uint64, len(n)), make([]int64, len(n))
	for i, v := range n {
		start[i] = 1
		count[i] = (v - 1) / 2
		stride[i] = 2
	}
	data := make([]float64, product(count))
	for i := 0; i < int(product(count)); i++ {
		data[i] = float64(i + 10)
	}
	return v.WriteFloat64StridedSlice(data, start, count, stride)
}

// testReadFloat64StridedSlice reads data from v and checks that it's the same as what
// was written by testWriteDouble. N is v.LenDim().
// This function is only used for testing.
func testReadFloat64StridedSlice(v Var, n []uint64) error {
	if len(n) == 0 {
		return nil // Don't test empty data.
	}
	start, count, stride := make([]uint64, len(n)), make([]uint64, len(n)), make([]int64, len(n))
	for i, v := range n {
		start[i] = 1
		count[i] = (v - 1) / 2
		stride[i] = 2
	}
	data := make([]float64, product(count))
	if err := v.ReadFloat64StridedSlice(data, start, count, stride); err != nil {
		return err
	}
	for i := 0; i < int(product(count)); i++ {
		if val := float64(i + 10); data[i] != val {
			return fmt.Errorf("strided slice data at position %d is %v; expected %v", i, data[i], val)
		}
	}
	return nil
}

func testReadFloat64At(v Var, n uint64) error {
	data := make([]float64, n)
	if err := v.ReadFloat64s(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		shape, _ := v.LenDims()
		coords, _ := UnravelIndex(uint64(i), shape)
		expected := data[i]
		val, _ := v.ReadFloat64At(coords)
		if val != expected {
			return fmt.Errorf("data at position %v is %v; expected %v", i, val, expected)
		}
	}
	return nil
}

func testWriteFloat64At(v Var, n uint64) error {
	shape, _ := v.LenDims()
	ndim := len(shape)
	coord := make([]uint64, ndim)
	for i := 0; i < ndim; i++ {
		for k := 0; k < ndim; k++ {
			coord[k] = uint64(i)
		}
		v.WriteFloat64At(coord, float64(i))
	}
	for i := 0; i < ndim; i++ {
		for k := 0; k < ndim; k++ {
			coord[k] = uint64(i)
		}
		val, _ := v.ReadFloat64At(coord)
		if val != float64(i) {
			return fmt.Errorf("data at position %v is %v; expected %v", coord, val, int(i))
		}
	}
	return nil
}
