// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.sh

package netcdf

import (
	"fmt"
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// WriteFloat writes data as the entire data for variable v.
func (v Var) WriteFloat(data []float32) error {
	if err := okData(v, NC_FLOAT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_float(C.int(v.ds), C.int(v.id), (*C.float)(unsafe.Pointer(&data[0]))))
}

// ReadFloat reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) ReadFloat(data []float32) error {
	if err := okData(v, NC_FLOAT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_float(C.int(v.ds), C.int(v.id), (*C.float)(unsafe.Pointer(&data[0]))))
}

// WriteFloat sets the value of attribute a to val.
func (a Attr) WriteFloat(val []float32) error {
	// We don't need okData here because netcdf library doesn't know
	// the length or type of the attribute yet.
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_float(C.int(a.v.ds), C.int(a.v.id), cname,
		C.nc_type(NC_FLOAT), C.size_t(len(val)), (*C.float)(unsafe.Pointer(&val[0]))))
}

// ReadFloat reads the entire attribute value into val.
func (a Attr) ReadFloat(val []float32) (err error) {
	if err := okData(a, NC_FLOAT, len(val)); err != nil {
		return err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	err = newError(C.nc_get_att_float(C.int(a.v.ds), C.int(a.v.id), cname,
		(*C.float)(unsafe.Pointer(&val[0]))))
	return
}

// FloatReader is a interface that allows reading a sequence of values of fixed length.
type FloatReader interface {
	Len() (n uint64, err error)
	ReadFloat(val []float32) (err error)
}

// GetFloat reads the entire data in r and returns it.
func GetFloat(r FloatReader) (data []float32, err error) {
	n, err := r.Len()
	if err != nil {
		return
	}
	data = make([]float32, n)
	err = r.ReadFloat(data)
	return
}

// TestWriteFloat writes somes data to v. N is v.Len().
// This function is only used for testing.
func testWriteFloat(v Var, n uint64) error {
	data := make([]float32, n)
	for i := 0; i < int(n); i++ {
		data[i] = float32(i + 10)
	}
	return v.WriteFloat(data)
}

// TestReadFloat reads data from v and checks that it's the same as what
// was written by testWriteFloat. N is v.Len().
// This function is only used for testing.
func testReadFloat(v Var, n uint64) error {
	data := make([]float32, n)
	if err := v.ReadFloat(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		if val := float32(i + 10); data[i] != val {
			return fmt.Errorf("data at position %d is %v; expected %v\n", i, data[i], val)
		}
	}
	return nil
}
