// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.sh

package netcdf

import (
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// PutInt writes data as the entire data for variable v.
func (v Var) PutInt(data []int32) error {
	if err := v.okData(NC_INT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_int(C.int(v.f), C.int(v.id), (*C.int)(unsafe.Pointer(&data[0]))))
}

// GetInt reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) GetInt(data []int32) error {
	if err := v.okData(NC_INT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_int(C.int(v.f), C.int(v.id), (*C.int)(unsafe.Pointer(&data[0]))))
}

// PutInt sets the value of attribute a to val.
func (a Attr) PutInt(val []int32) error {
	// TODO: check Type is NC_DOUBLE and len(val) is corrent
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_int(C.int(a.v.f), C.int(a.v.id), cname,
		C.nc_type(NC_INT), C.size_t(len(val)), (*C.int)(unsafe.Pointer(&val[0]))))
}

// GetInt returns the attribute value.
func (a Attr) GetInt() (val []int32, err error) {
	// TODO: check Type is NC_DOUBLE
	n, err := a.Len()
	if err != nil {
		return nil, err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	val = make([]int32, n)
	err = newError(C.nc_get_att_int(C.int(a.v.f), C.int(a.v.id), cname,
		(*C.int)(unsafe.Pointer(&val[0]))))
	return
}
