// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.sh

package netcdf

import (
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// PutShort writes data as the entire data for variable v.
func (v Var) PutShort(data []int16) error {
	if err := v.okData(NC_SHORT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_short(C.int(v.f), C.int(v.id), (*C.short)(unsafe.Pointer(&data[0]))))
}

// GetShort reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) GetShort(data []int16) error {
	if err := v.okData(NC_SHORT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_short(C.int(v.f), C.int(v.id), (*C.short)(unsafe.Pointer(&data[0]))))
}

// PutShort sets the value of attribute a to val.
func (a Attr) PutShort(val []int16) error {
	// TODO: check Type is NC_DOUBLE and len(val) is corrent
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_short(C.int(a.v.f), C.int(a.v.id), cname,
		C.nc_type(NC_SHORT), C.size_t(len(val)), (*C.short)(unsafe.Pointer(&val[0]))))
}

// GetShort returns the attribute value.
func (a Attr) GetShort() (val []int16, err error) {
	// TODO: check Type is NC_DOUBLE
	n, err := a.Len()
	if err != nil {
		return nil, err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	val = make([]int16, n)
	err = newError(C.nc_get_att_short(C.int(a.v.f), C.int(a.v.id), cname,
		(*C.short)(unsafe.Pointer(&val[0]))))
	return
}
