// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.go
// DO NOT EDIT (except nc_double.go).

package netcdf

import (
	"fmt"
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// WriteInt16s writes data as the entire data for variable v.
func (v Var) WriteInt16s(data []int16) error {
	if err := okData(v, SHORT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_short(C.int(v.ds), C.int(v.id), (*C.short)(unsafe.Pointer(&data[0]))))
}

// ReadInt16s reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) ReadInt16s(data []int16) error {
	if err := okData(v, SHORT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_short(C.int(v.ds), C.int(v.id), (*C.short)(unsafe.Pointer(&data[0]))))
}

// WriteInt16s sets the value of attribute a to val.
func (a Attr) WriteInt16s(val []int16) error {
	// We don't need okData here because netcdf library doesn't know
	// the length or type of the attribute yet.
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_short(C.int(a.v.ds), C.int(a.v.id), cname,
		C.nc_type(SHORT), C.size_t(len(val)), (*C.short)(unsafe.Pointer(&val[0]))))
}

// ReadInt16s reads the entire attribute value into val.
func (a Attr) ReadInt16s(val []int16) (err error) {
	if err := okData(a, SHORT, len(val)); err != nil {
		return err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	err = newError(C.nc_get_att_short(C.int(a.v.ds), C.int(a.v.id), cname,
		(*C.short)(unsafe.Pointer(&val[0]))))
	return
}

// ReadInt16At returns a value via index position
func (v Var) ReadInt16At(idx []uint64) (val int16, err error) {
	var dimPtr *C.size_t
	if len(idx) > 0 {
		dimPtr = (*C.size_t)(unsafe.Pointer(&idx[0]))
	}
	err = newError(C.nc_get_var1_short(C.int(v.ds), C.int(v.id),
		dimPtr, (*C.short)(unsafe.Pointer(&val))))
	return
}

// WriteInt16At sets a value via its index position
func (v Var) WriteInt16At(idx []uint64, val int16) (err error) {
	var dimPtr *C.size_t
	if len(idx) > 0 {
		dimPtr = (*C.size_t)(unsafe.Pointer(&idx[0]))
	}
	err = newError(C.nc_put_var1_short(C.int(v.ds), C.int(v.id),
		dimPtr, (*C.short)(unsafe.Pointer(&val))))
	return
}

// WriteInt16Slice writes data as a slice of variable v. The slice is specified by start and count:
// https://www.unidata.ucar.edu/software/netcdf/docs/programming_notes.html#specify_hyperslab.
func (v Var) WriteInt16Slice(data []int16, start, count []uint64) error {
	if err := okDataSlice(v, SHORT, len(data), start, count); err != nil {
		return err
	}
	return newError(C.nc_put_vara_short(C.int(v.ds), C.int(v.id),
		(*C.size_t)(unsafe.Pointer(&start[0])),
		(*C.size_t)(unsafe.Pointer(&count[0])),
		(*C.short)(unsafe.Pointer(&data[0])),
	))
}

// ReadInt16Slice reads a slice of variable v into data, which must have enough
// space for all the values. The slice is specified by start and count:
// https://www.unidata.ucar.edu/software/netcdf/docs/programming_notes.html#specify_hyperslab.
func (v Var) ReadInt16Slice(data []int16, start, count []uint64) error {
	if err := okDataSlice(v, SHORT, len(data), start, count); err != nil {
		return err
	}
	return newError(C.nc_get_vara_short(C.int(v.ds), C.int(v.id),
		(*C.size_t)(unsafe.Pointer(&start[0])),
		(*C.size_t)(unsafe.Pointer(&count[0])),
		(*C.short)(unsafe.Pointer(&data[0])),
	))
}

// WriteInt16StridedSlice writes data as a slice of variable v. The slice is specified by start, count and stride:
// https://www.unidata.ucar.edu/software/netcdf/docs/programming_notes.html#specify_hyperslab.
func (v Var) WriteInt16StridedSlice(data []int16, start, count []uint64, stride []int64) error {
	if err := okDataStride(v, SHORT, len(data), start, count, stride); err != nil {
		return err
	}
	return newError(C.nc_put_vars_short(C.int(v.ds), C.int(v.id),
		(*C.size_t)(unsafe.Pointer(&start[0])),
		(*C.size_t)(unsafe.Pointer(&count[0])),
		(*C.ptrdiff_t)(unsafe.Pointer(&stride[0])),
		(*C.short)(unsafe.Pointer(&data[0])),
	))
}

// ReadInt16StridedSlice reads a strided slice of variable v into data, which must have enough
// space for all the values. The slice is specified by start, count and stride:
// https://www.unidata.ucar.edu/software/netcdf/docs/programming_notes.html#specify_hyperslab.
func (v Var) ReadInt16StridedSlice(data []int16, start, count []uint64, stride []int64) error {
	if err := okDataStride(v, SHORT, len(data), start, count, stride); err != nil {
		return err
	}
	return newError(C.nc_get_vars_short(C.int(v.ds), C.int(v.id),
		(*C.size_t)(unsafe.Pointer(&start[0])),
		(*C.size_t)(unsafe.Pointer(&count[0])),
		(*C.ptrdiff_t)(unsafe.Pointer(&stride[0])),
		(*C.short)(unsafe.Pointer(&data[0])),
	))
}

// Int16sReader is a interface that allows reading a sequence of values of fixed length.
type Int16sReader interface {
	Len() (n uint64, err error)
	ReadInt16s(val []int16) (err error)
}

// GetInt16s reads the entire data in r and returns it.
func GetInt16s(r Int16sReader) (data []int16, err error) {
	n, err := r.Len()
	if err != nil {
		return
	}
	data = make([]int16, n)
	err = r.ReadInt16s(data)
	return
}

// testReadInt16s writes somes data to v. N is v.Len().
// This function is only used for testing.
func testWriteInt16s(v Var, n uint64) error {
	data := make([]int16, n)
	for i := 0; i < int(n); i++ {
		data[i] = int16(i + 10)
	}
	return v.WriteInt16s(data)
}

// testReadInt16s reads data from v and checks that it's the same as what
// was written by testWriteDouble. N is v.Len().
// This function is only used for testing.
func testReadInt16s(v Var, n uint64) error {
	data := make([]int16, n)
	if err := v.ReadInt16s(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		if val := int16(i + 10); data[i] != val {
			return fmt.Errorf("data at position %d is %v; expected %v", i, data[i], val)
		}
	}
	return nil
}

// testWriteInt16Slice writes somes data to v. N is v.LenDim().
// This function is only used for testing.
func testWriteInt16Slice(v Var, n []uint64) error {
	if len(n) == 0 {
		return nil // Don't test empty data.
	}
	start, count := make([]uint64, len(n)), make([]uint64, len(n))
	for i, v := range n {
		start[i] = v / 2
		count[i] = v / 2
	}
	data := make([]int16, product(count))
	for i := 0; i < int(product(count)); i++ {
		data[i] = int16(i + 10)
	}
	return v.WriteInt16Slice(data, start, count)
}

// testReadInt16Slice reads data from v and checks that it's the same as what
// was written by testWriteDouble. N is v.LenDim().
// This function is only used for testing.
func testReadInt16Slice(v Var, n []uint64) error {
	if len(n) == 0 {
		return nil // Don't test empty data.
	}
	start, count := make([]uint64, len(n)), make([]uint64, len(n))
	for i, v := range n {
		start[i] = v / 2
		count[i] = v / 2
	}
	data := make([]int16, product(count))
	if err := v.ReadInt16Slice(data, start, count); err != nil {
		return err
	}
	for i := 0; i < int(product(count)); i++ {
		if val := int16(i + 10); data[i] != val {
			return fmt.Errorf("strided slice data at position %d is %v; expected %v", i, data[i], val)
		}
	}
	return nil
}

// testWriteInt16StridedSlice writes somes data to v. N is v.LenDim().
// This function is only used for testing.
func testWriteInt16StridedSlice(v Var, n []uint64) error {
	if len(n) == 0 {
		return nil // Don't test empty data.
	}
	start, count, stride := make([]uint64, len(n)), make([]uint64, len(n)), make([]int64, len(n))
	for i, v := range n {
		start[i] = 1
		count[i] = (v - 1) / 2
		stride[i] = 2
	}
	data := make([]int16, product(count))
	for i := 0; i < int(product(count)); i++ {
		data[i] = int16(i + 10)
	}
	return v.WriteInt16StridedSlice(data, start, count, stride)
}

// testReadInt16StridedSlice reads data from v and checks that it's the same as what
// was written by testWriteDouble. N is v.LenDim().
// This function is only used for testing.
func testReadInt16StridedSlice(v Var, n []uint64) error {
	if len(n) == 0 {
		return nil // Don't test empty data.
	}
	start, count, stride := make([]uint64, len(n)), make([]uint64, len(n)), make([]int64, len(n))
	for i, v := range n {
		start[i] = 1
		count[i] = (v - 1) / 2
		stride[i] = 2
	}
	data := make([]int16, product(count))
	if err := v.ReadInt16StridedSlice(data, start, count, stride); err != nil {
		return err
	}
	for i := 0; i < int(product(count)); i++ {
		if val := int16(i + 10); data[i] != val {
			return fmt.Errorf("strided slice data at position %d is %v; expected %v", i, data[i], val)
		}
	}
	return nil
}

func testReadInt16At(v Var, n uint64) error {
	data := make([]int16, n)
	if err := v.ReadInt16s(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		shape, _ := v.LenDims()
		coords, _ := UnravelIndex(uint64(i), shape)
		expected := data[i]
		val, _ := v.ReadInt16At(coords)
		if val != expected {
			return fmt.Errorf("data at position %v is %v; expected %v", i, val, expected)
		}
	}
	return nil
}

func testWriteInt16At(v Var, n uint64) error {
	shape, _ := v.LenDims()
	ndim := len(shape)
	coord := make([]uint64, ndim)
	for i := 0; i < ndim; i++ {
		for k := 0; k < ndim; k++ {
			coord[k] = uint64(i)
		}
		v.WriteInt16At(coord, int16(i))
	}
	for i := 0; i < ndim; i++ {
		for k := 0; k < ndim; k++ {
			coord[k] = uint64(i)
		}
		val, _ := v.ReadInt16At(coord)
		if val != int16(i) {
			return fmt.Errorf("data at position %v is %v; expected %v", coord, val, int(i))
		}
	}
	return nil
}
