// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.go
// DO NOT EDIT (except nc_double.go).

package netcdf

import (
	"fmt"
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// WriteInt16s writes data as the entire data for variable v.
func (v Var) WriteInt16s(data []int16) error {
	if err := okData(v, SHORT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_short(C.int(v.ds), C.int(v.id), (*C.short)(unsafe.Pointer(&data[0]))))
}

// ReadInt16s reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) ReadInt16s(data []int16) error {
	if err := okData(v, SHORT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_short(C.int(v.ds), C.int(v.id), (*C.short)(unsafe.Pointer(&data[0]))))
}

// WriteInt16s sets the value of attribute a to val.
func (a Attr) WriteInt16s(val []int16) error {
	// We don't need okData here because netcdf library doesn't know
	// the length or type of the attribute yet.
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_short(C.int(a.v.ds), C.int(a.v.id), cname,
		C.nc_type(SHORT), C.size_t(len(val)), (*C.short)(unsafe.Pointer(&val[0]))))
}

// ReadInt16s reads the entire attribute value into val.
func (a Attr) ReadInt16s(val []int16) (err error) {
	if err := okData(a, SHORT, len(val)); err != nil {
		return err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	err = newError(C.nc_get_att_short(C.int(a.v.ds), C.int(a.v.id), cname,
		(*C.short)(unsafe.Pointer(&val[0]))))
	return
}

// Int16sReader is a interface that allows reading a sequence of values of fixed length.
type Int16sReader interface {
	Len() (n uint64, err error)
	ReadInt16s(val []int16) (err error)
}

// GetInt16s reads the entire data in r and returns it.
func GetInt16s(r Int16sReader) (data []int16, err error) {
	n, err := r.Len()
	if err != nil {
		return
	}
	data = make([]int16, n)
	err = r.ReadInt16s(data)
	return
}

// testReadInt16s writes somes data to v. N is v.Len().
// This function is only used for testing.
func testWriteInt16s(v Var, n uint64) error {
	data := make([]int16, n)
	for i := 0; i < int(n); i++ {
		data[i] = int16(i + 10)
	}
	return v.WriteInt16s(data)
}

// testReadInt16s reads data from v and checks that it's the same as what
// was written by testWriteDouble. N is v.Len().
// This function is only used for testing.
func testReadInt16s(v Var, n uint64) error {
	data := make([]int16, n)
	if err := v.ReadInt16s(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		if val := int16(i + 10); data[i] != val {
			return fmt.Errorf("data at position %d is %v; expected %v\n", i, data[i], val)
		}
	}
	return nil
}
