// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.sh

package netcdf

import (
	"fmt"
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// WriteUint64 writes data as the entire data for variable v.
func (v Var) WriteUint64(data []uint64) error {
	if err := okData(v, NC_UINT64, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_ulonglong(C.int(v.ds), C.int(v.id), (*C.ulonglong)(unsafe.Pointer(&data[0]))))
}

// ReadUint64 reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) ReadUint64(data []uint64) error {
	if err := okData(v, NC_UINT64, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_ulonglong(C.int(v.ds), C.int(v.id), (*C.ulonglong)(unsafe.Pointer(&data[0]))))
}

// WriteUint64 sets the value of attribute a to val.
func (a Attr) WriteUint64(val []uint64) error {
	// We don't need okData here because netcdf library doesn't know
	// the length or type of the attribute yet.
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_ulonglong(C.int(a.v.ds), C.int(a.v.id), cname,
		C.nc_type(NC_UINT64), C.size_t(len(val)), (*C.ulonglong)(unsafe.Pointer(&val[0]))))
}

// ReadUint64 reads the entire attribute value into val.
func (a Attr) ReadUint64(val []uint64) (err error) {
	if err := okData(a, NC_UINT64, len(val)); err != nil {
		return err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	err = newError(C.nc_get_att_ulonglong(C.int(a.v.ds), C.int(a.v.id), cname,
		(*C.ulonglong)(unsafe.Pointer(&val[0]))))
	return
}

// Uint64Reader is a interface that allows reading a sequence of values of fixed length.
type Uint64Reader interface {
	Len() (n uint64, err error)
	ReadUint64(val []uint64) (err error)
}

// GetUint64 reads the entire data in r and returns it.
func GetUint64(r Uint64Reader) (data []uint64, err error) {
	n, err := r.Len()
	if err != nil {
		return
	}
	data = make([]uint64, n)
	err = r.ReadUint64(data)
	return
}

// TestWriteUint64 writes somes data to v. N is v.Len().
// This function is only used for testing.
func testWriteUint64(v Var, n uint64) error {
	data := make([]uint64, n)
	for i := 0; i < int(n); i++ {
		data[i] = uint64(i + 10)
	}
	return v.WriteUint64(data)
}

// TestReadUint64 reads data from v and checks that it's the same as what
// was written by testWriteUint64. N is v.Len().
// This function is only used for testing.
func testReadUint64(v Var, n uint64) error {
	data := make([]uint64, n)
	if err := v.ReadUint64(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		if val := uint64(i + 10); data[i] != val {
			return fmt.Errorf("data at position %d is %f; expected %f\n", i, data[i], val)
		}
	}
	return nil
}
