// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.sh

package netcdf

import (
	"fmt"
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// WriteUint writes data as the entire data for variable v.
func (v Var) WriteUint(data []uint32) error {
	if err := okData(v, NC_UINT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_uint(C.int(v.f), C.int(v.id), (*C.uint)(unsafe.Pointer(&data[0]))))
}

// ReadUint reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) ReadUint(data []uint32) error {
	if err := okData(v, NC_UINT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_uint(C.int(v.f), C.int(v.id), (*C.uint)(unsafe.Pointer(&data[0]))))
}

// WriteUint sets the value of attribute a to val.
func (a Attr) WriteUint(val []uint32) error {
	// We don't need okData here because netcdf library doesn't know
	// the length or type of the attribute yet.
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_uint(C.int(a.v.f), C.int(a.v.id), cname,
		C.nc_type(NC_UINT), C.size_t(len(val)), (*C.uint)(unsafe.Pointer(&val[0]))))
}

// ReadUint reads the entire attribute value into val.
func (a Attr) ReadUint(val []uint32) (err error) {
	if err := okData(a, NC_UINT, len(val)); err != nil {
		return err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	err = newError(C.nc_get_att_uint(C.int(a.v.f), C.int(a.v.id), cname,
		(*C.uint)(unsafe.Pointer(&val[0]))))
	return
}

// UintReader is a interface that allows reading a sequence of values of fixed length.
type UintReader interface {
	Len() (n uint64, err error)
	ReadUint(val []uint32) (err error)
}

// GetUint reads the entire data in r and returns it.
func GetUint(r UintReader) (data []uint32, err error) {
	n, err := r.Len()
	if err != nil {
		return
	}
	data = make([]uint32, n)
	err = r.ReadUint(data)
	return
}

// TestWriteUint writes somes data to v. N is v.Len().
// This function is only used for testing.
func testWriteUint(v Var, n uint64) error {
	data := make([]uint32, n)
	for i := 0; i < int(n); i++ {
		data[i] = uint32(i + 10)
	}
	return v.WriteUint(data)
}

// TestReadUint reads data from v and checks that it's the same as what
// was written by testWriteUint. N is v.Len().
// This function is only used for testing.
func testReadUint(v Var, n uint64) error {
	data := make([]uint32, n)
	if err := v.ReadUint(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		if val := uint32(i + 10); data[i] != val {
			return fmt.Errorf("data at position %d is %f; expected %f\n", i, data[i], val)
		}
	}
	return nil
}
