// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.sh

package netcdf

import (
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// PutUint writes data as the entire data for variable v.
func (v Var) PutUint(data []uint32) error {
	if err := v.okData(NC_UINT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_uint(C.int(v.f), C.int(v.id), (*C.uint)(unsafe.Pointer(&data[0]))))
}

// GetUint reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) GetUint(data []uint32) error {
	if err := v.okData(NC_UINT, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_uint(C.int(v.f), C.int(v.id), (*C.uint)(unsafe.Pointer(&data[0]))))
}

// PutUint sets the value of attribute a to val.
func (a Attr) PutUint(val []uint32) error {
	// TODO: check Type is NC_DOUBLE and len(val) is corrent
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_uint(C.int(a.v.f), C.int(a.v.id), cname,
		C.nc_type(NC_UINT), C.size_t(len(val)), (*C.uint)(unsafe.Pointer(&val[0]))))
}

// GetUint returns the attribute value.
func (a Attr) GetUint() (val []uint32, err error) {
	// TODO: check Type is NC_DOUBLE
	n, err := a.Len()
	if err != nil {
		return nil, err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	val = make([]uint32, n)
	err = newError(C.nc_get_att_uint(C.int(a.v.f), C.int(a.v.id), cname,
		(*C.uint)(unsafe.Pointer(&val[0]))))
	return
}
