// Copyright 2014 The Go-NetCDF Authors. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE file.

// These files are autogenerated from nc_double.go using generate.go
// DO NOT EDIT (except nc_double.go).

package netcdf

import (
	"fmt"
	"unsafe"
)

// #include <stdlib.h>
// #include <netcdf.h>
import "C"

// WriteUint8s writes data as the entire data for variable v.
func (v Var) WriteUint8s(data []uint8) error {
	if err := okData(v, UBYTE, len(data)); err != nil {
		return err
	}
	return newError(C.nc_put_var_uchar(C.int(v.ds), C.int(v.id), (*C.uchar)(unsafe.Pointer(&data[0]))))
}

// ReadUint8s reads the entire variable v into data, which must have enough
// space for all the values (i.e. len(data) must be at least v.Len()).
func (v Var) ReadUint8s(data []uint8) error {
	if err := okData(v, UBYTE, len(data)); err != nil {
		return err
	}
	return newError(C.nc_get_var_uchar(C.int(v.ds), C.int(v.id), (*C.uchar)(unsafe.Pointer(&data[0]))))
}

// WriteUint8s sets the value of attribute a to val.
func (a Attr) WriteUint8s(val []uint8) error {
	// We don't need okData here because netcdf library doesn't know
	// the length or type of the attribute yet.
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	return newError(C.nc_put_att_uchar(C.int(a.v.ds), C.int(a.v.id), cname,
		C.nc_type(UBYTE), C.size_t(len(val)), (*C.uchar)(unsafe.Pointer(&val[0]))))
}

// ReadUint8s reads the entire attribute value into val.
func (a Attr) ReadUint8s(val []uint8) (err error) {
	if err := okData(a, UBYTE, len(val)); err != nil {
		return err
	}
	cname := C.CString(a.name)
	defer C.free(unsafe.Pointer(cname))
	err = newError(C.nc_get_att_uchar(C.int(a.v.ds), C.int(a.v.id), cname,
		(*C.uchar)(unsafe.Pointer(&val[0]))))
	return
}

// Uint8sReader is a interface that allows reading a sequence of values of fixed length.
type Uint8sReader interface {
	Len() (n uint64, err error)
	ReadUint8s(val []uint8) (err error)
}

// GetUint8s reads the entire data in r and returns it.
func GetUint8s(r Uint8sReader) (data []uint8, err error) {
	n, err := r.Len()
	if err != nil {
		return
	}
	data = make([]uint8, n)
	err = r.ReadUint8s(data)
	return
}

// testReadUint8s writes somes data to v. N is v.Len().
// This function is only used for testing.
func testWriteUint8s(v Var, n uint64) error {
	data := make([]uint8, n)
	for i := 0; i < int(n); i++ {
		data[i] = uint8(i + 10)
	}
	return v.WriteUint8s(data)
}

// testReadUint8s reads data from v and checks that it's the same as what
// was written by testWriteDouble. N is v.Len().
// This function is only used for testing.
func testReadUint8s(v Var, n uint64) error {
	data := make([]uint8, n)
	if err := v.ReadUint8s(data); err != nil {
		return err
	}
	for i := 0; i < int(n); i++ {
		if val := uint8(i + 10); data[i] != val {
			return fmt.Errorf("data at position %d is %v; expected %v\n", i, data[i], val)
		}
	}
	return nil
}
